apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webpm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-youwol
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webpm
                port:
                  number: 80
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: webpm-tls
