apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
plugin: prometheus

metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  {{- .Files.Get "prometheus-plugin.yaml" | nindent 2}}
