apiVersion: v2
name: prometheus-stack
version: 1.0.0
appVersion: 39.11.0

dependencies:
  - name: kube-prometheus-stack
    version: 39.11.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: lib-configuration
    version: 0.0.1
    repository: https://gitlab.com/api/v4/projects/15166395/packages/helm/stable/
