fullnameOverride: prometheus-stack
kube-prometheus-stack:
  grafana:
    sidecar:
      skipTlsVerify: true
    grafana.ini:
      server:
        domain: "tooling.youwol.com"
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true
    ingress:
      enabled: true
      annotations:
        # modify to match your certificates issuer
        cert-manager.io/cluster-issuer: letsencrypt-youwol
      ingressClassName: nginx
      hosts:
        - "tooling.youwol.com"
      path: "/grafana"
      tls:
      - hosts:
        - "tooling.youwol.com"
        secretName: tooling-tls
    admin:
      existingSecret: grafana-secret
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
  defaultRules:
    rules:
      kubeControllerManager: false
      kubeProxy: false
      kubeSchedulerAlerting: false
