fullnameOverride: prometheus-stack
kube-prometheus-stack:
  grafana:
    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-auth-client
          key: client-secret
    sidecar:
      skipTlsVerify: true
      dashboards:
        provider:
          foldersFromFilesStructure: true
        annotations:
          k8s-sidecar-target-directory: "/tmp/dashboards/prometheus-stack"
    grafana.ini:
      server:
        domain: "tooling.youwol.com"
        root_url: "https://%(domain)s/grafana"
        serve_from_sub_path: true
#      auth.basic:
#        enabled: false
      auth.generic_oauth:
        enabled: true
        name: "Keycloak realm Kubernetes"
        allow_sign_up: true
        client_id: grafana-auth
        scopes: openid email profile offline_access
        email_attribute_path: email
        login_attribute_path: username
        name_attribute_path: full_name
        role_attribute_path: grafana_role
        role_attribute_strict: true
        auth_url: "https://platform.youwol.com/auth/realms/kubernetes/protocol/openid-connect/auth"
        token_url: "https://platform.youwol.com/auth/realms/kubernetes/protocol/openid-connect/token"
        signout_redirect_url: "https://platform.youwol.com/auth/realms/kubernetes/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2F%(domain)s/grafana/%2Flogin"
        allow_assign_grafana_admin: true
        use_refresh_token: true
        auto_login: true
    ingress:
      enabled: true
      annotations:
        # modify to match your certificates issuer
        cert-manager.io/cluster-issuer: letsencrypt-youwol
      ingressClassName: nginx
      hosts:
        - "tooling.youwol.com"
      path: "/grafana"
      tls:
      - hosts:
        - "tooling.youwol.com"
        secretName: tooling-tls
    admin:
      existingSecret: grafana-admin
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
  defaultRules:
    rules:
      kubeControllerManager: false
      kubeProxy: false
      kubeSchedulerAlerting: false
