{{- $keys := list "keycloak_admin_client_secret" }}
{{- $args := dict  "root" . "name" "keycloak-admin-secret" "keys" $keys }}
{{- include "lib-configuration.secret" $args }}
{{/* this is not a reporty */}}
