apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-assets.service-default-route.name" . }}
  annotations:
    konghq.com/host-header: "default-route"
  labels:
    {{- include "static-assets.labels" . | nindent 4 }}
    app.kubernetes.io/component: default-route
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "static-assets.selectorLabels" . | nindent 4 }}
