apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-assets.fullname" . }}
  labels:
    {{- include "static-assets.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      {{- include "static-assets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-assets.selectorLabels" . | nindent 8 }}
      annotations:
        youwol.com/configmap-sha: {{ .Files.Get "maintenance-details.txt" | sha1sum }}
    spec:
      volumes:
        - name: nginx-customization
          emptyDir: {}
        - name: includes-maintenance
          configMap:
            name: {{ include "static-assets.includes-maintenance-configmap.name" . }}
        - name: assets-zip
          configMap:
            name: {{ include "static-assets.assets-zip-configmap.name" . }} 
      initContainers:
        - name: unzip-assets
          image: busybox:1.35.0-uclibc
          command: [
          "sh", "-c",
          "ls -lah /assets && \
          base64 -d /assets/assets.zip > /tmp/assets.zip && \
          unzip /tmp/assets.zip -d /tmp && \
          mv /tmp/assets/* /git && \
          echo 'Files in /git:' && \
          ls /git" ]  # "sh", "-c", "unzip /assets/static-assets-assets-zip -d /git"
          volumeMounts:
            - mountPath: /assets
              name: assets-zip
            - mountPath: /git
              name: nginx-customization
      containers:
        - name: nginx
          image: nginx
          env:
            - name: PLATFORM_HOST
              value: {{ include "static-assets.platform-host" . }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/templates/
              name: nginx-customization
              subPath: templates
            - mountPath: /usr/share/nginx
              name: nginx-customization
              subPath: sites
            - mountPath: /usr/share/nginx/includes/maintenance
              name: includes-maintenance
