apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "static-assets.service-static-assets.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "static-assets"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  labels:
    {{- include "static-assets.labels" . | nindent 4 }}
    app.kubernetes.io/component: static-assets
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "static-assets.platform-host" . }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "static-assets.service-static-assets.name" . }}
                port:
                  name: http
            pathType: Prefix
            path: /static(/|$)(.*)
