ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: "Local"
      annotations:
        service.beta.kubernetes.io/ovh-loadbalancer-proxy-protocol: "v2"
    config:
      use-proxy-protocol: "true"
      real-ip-header: "proxy_protocol"
      proxy-body-size: "10m"
      # values token from `kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath="{.metadata.annotations.lb\.k8s\.ovh\.net/egress-ips}"`
      proxy-real-ip-cidr: "10.199.194.165/32,10.199.193.53/32,10.199.194.154/32,10.199.194.35/32"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        jobLabel: ingress-nginx
