assets-gatewayBaseUrl: "https://platform.int.youwol.com/api/assets-gateway/"
default_cdn_client_version: "latest"
default_webpm_client_version: "latest"
oidc_issuer: "https://platform.int.youwol.com/auth/realms/youwol"
client_id: "webpm"
configID: "webpm"
host: "https://webpm.org"
root_redirection: "https://platform.int.youwol.com/applications/@youwol/webpm/latest"
