assets-gatewayBaseUrl: "http://assets-gateway.apps.svc.cluster.local"
default_cdn_client_version: "latest"
oidc_issuer: "https://platform.youwol.com/auth/realms/youwol"
client_id: "webpm"
configID: "webpm"
host: "https://webpm.org"
root_redirection: "https://platform.youwol.com/applications/@youwol/webpm/latest"
