version: 1
disable_existing_loggers: False

formatters:
    colored:
      (): colorlog.ColoredFormatter
      format: '[%(log_color)s%(asctime)s] %(levelname)8s [%(pathname)s.%(funcName)s#%(lineno)d]%(reset)s %(name)s:%(message_log_color)s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
      log_colors:
        DEBUG: fg_thin_cyan
        INFO: fg_green
        WARNING: fg_yellow
        ERROR: fg_red
        CRITICAL: fg_red,bg_white
      secondary_log_colors:
        message:
          DEBUG: fg_bold_cyan
          INFO: fg_bold_green
          WARNING: fg_bold_yellow
          ERROR: fg_bold_red
          CRITICAL: fg_bold_red,bg_white
    simple:
      format: '[%(asctime)s] %(levelname)8s [%(pathname)s.%(funcName)s#%(lineno)d] %(name)s: %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: colored
        stream: ext://sys.stderr

root:
    level: DEBUG
    handlers: [console]
