scylla-manager:
  scylla:
    developerMode: true
    scyllaImage:
      tag: 5.4.5
    agentImage:
      tag: 3.2.7
    datacenter: manager-dc
    racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 10Gi
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
  serviceMonitor:
    create: true
