{{ $hostname := (lookup "v1" "ConfigMap" "apps" "cluster-config").data.clusterDomain}}
{{/*{{ $hostname := "platform.int.youwol.com"}}*/}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.ingress.name" . }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-youwol
    konghq.com/https-redirect-status-code: "301"
    konghq.com/protocols: https
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  ingressClassName: kong
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
            path: /auth
            pathType: Prefix
  tls:
    - hosts:
        - {{ $hostname }}
      secretName: platform-tls
