{{ $hostname := (lookup "v1" "ConfigMap" "apps" "cluster-config").data.clusterDomain}}
{{/*{{ $hostname := "platform.dev.youwol.com" }}*/}}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ include "keycloak.keycloak.name" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  ingress:
    enabled: false
  instances: 2
  {{- if .Values.keycloakImage }}
  image: {{ include "keycloak.image" . }}
  {{- if .Values.keycloakImage.imagePullSecrets }}
  imagePullSecrets:
    - name: {{ .Values.keycloakImage.imagePullSecrets }}
  {{- end }}
  {{- end }}
  hostname:
    hostname: {{ $hostname }}
  proxy:
    headers: "xforwarded"
  http:
    httpEnabled: true
  db:
    usernameSecret:
      name: keycloak-pguser-keycloak
      key: user
    passwordSecret:
      name: keycloak-pguser-keycloak
      key: password
  additionalOptions:
    - name: db-url
      secret:
        name: keycloak-pguser-keycloak
        key: jdbc-uri
    - name: http-relative-path
      value: "/auth"
  bootstrapAdmin:
    user:
      secret: "keycloak-bootstrap-admin"
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: clone-theme
            image: alpine/git
            args:
              - clone
              - --branch
              - {{ .Values.youwolKeycloakTheme.branchOrTag }}
              - --depth
              - "1"
              - {{ .Values.youwolKeycloakTheme.url }}
              - .
            volumeMounts:
              - name: youwol-keycloak-theme
                mountPath: /git
        containers:
          - volumeMounts:
              - name: youwol-keycloak-theme
                mountPath: /opt/keycloak/themes/youwol
                subPath: theme
        volumes:
          - name: youwol-keycloak-theme
            emptyDir: {}
