{{ $hostname := (lookup "v1" "ConfigMap" "apps" "cluster-config").data.clusterDomain}}
{{/*{{ $hostname := "platform.dev.youwol.com" }}*/}}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  hostname: {{ $hostname }}
  tlsSecret: INSECURE-DISABLE
  disableDefaultIngress: true
  serverConfiguration:
    - name: features
      value: "token-exchange"
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
    - name: proxy
      value: "edge"
    - name: http-relative-path
      value: "/auth"
    - name: db
      value: postgres
    - name: db-url-host
      secret:
        name: keycloak-db-pguser-keycloak-db
        key: host
    - name: db-url-port
      secret:
        name: keycloak-db-pguser-keycloak-db
        key: port
    - name: db-url-database
      secret:
        name: keycloak-db-pguser-keycloak-db
        key: dbname
    - name: db-username
      secret:
        name: keycloak-db-pguser-keycloak-db
        key: user
    - name: db-password
      secret:
        name: keycloak-db-pguser-keycloak-db
        key: password
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: clone-theme
            image: alpine/git
            args:
              - clone
              - --branch
              - {{ .Values.youwolKeycloakTheme.branchOrTag }}
              - --depth
              - "1"
              - {{ .Values.youwolKeycloakTheme.url }}
              - .
            volumeMounts:
              - name: youwol-keycloak-theme
                mountPath: /git
        containers:
          - volumeMounts:
              - name: youwol-keycloak-theme
                mountPath: /opt/keycloak/themes/youwol
                subPath: theme
        volumes:
          - name: youwol-keycloak-theme
            emptyDir: {}
