apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "keycloak.postgres.name" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 10G

  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10G

  postgresVersion: 15
  databaseInitSQL:
    key: init.sql
    name: {{ include "keycloak-postgres-db-init-sql.name" . }}
