apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "keycloak.postgres.name" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            full:         "37 23 * * sun"
            differential: "24 22 * *   *"
            incremental:  "12  * * *   *"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 20G

  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20G

  postgresVersion: 15
  databaseInitSQL:
    key: init.sql
    name: {{ include "keycloak-postgres-db-init-sql.name" . }}
