apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "keycloakOperator.name" . }}
  labels:
    {{- include "keycloakOperator.labels" . | indent 4 }}

spec:
  replicas: 1

  selector:
    matchLabels:
      {{- include "keycloakOperator.selectorLabels" . | indent 6 }}

  template:

    metadata:
      labels:
        {{- include "keycloakOperator.selectorLabels" . | indent 8 }}

    spec:
      serviceAccountName: {{ include "keycloakOperator.name" . }}

      containers:
        - name: keycloak-operator
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_KEYCLOAK_IMAGE
              value: {{ include "keycloakOperator.keycloakImage" . }}

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP

          image: {{ include "keycloakOperator.operatorImage" . }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
