apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-operator.name" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "keycloak-operator.selector-labels" . | nindent 4 }}
  type: ClusterIP
