{{- $minioScyllaBackupSecret := lookup "v1" "Secret" "infra" "minio-scylla-backup-secret"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-agent-config-secret
stringData:
  scylla-manager-agent.yaml: |
     s3:
        access_key_id: scylla-backup
        secret_access_key: {{ get $minioScyllaBackupSecret.data "scylla-backup-secret-key" | b64dec }}
        provider: Minio
        endpoint: http://minio.infra.svc.cluster.local:9000
